Return-Path: <linux-kernel+bounces-356873-lists+linux-kernel=lfdr.de@vger.kernel.org>
X-Original-To: lists+linux-kernel@lfdr.de
Delivered-To: lists+linux-kernel@lfdr.de
Received: from sv.mirrors.kernel.org (sv.mirrors.kernel.org [139.178.88.99])
	by mail.lfdr.de (Postfix) with ESMTPS id 3545B9967FE
	for <lists+linux-kernel@lfdr.de>; Wed,  9 Oct 2024 13:05:32 +0200 (CEST)
Received: from smtp.subspace.kernel.org (wormhole.subspace.kernel.org [52.25.139.140])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by sv.mirrors.kernel.org (Postfix) with ESMTPS id E59EE28B1BD
	for <lists+linux-kernel@lfdr.de>; Wed,  9 Oct 2024 11:05:27 +0000 (UTC)
Received: from localhost.localdomain (localhost.localdomain [127.0.0.1])
	by smtp.subspace.kernel.org (Postfix) with ESMTP id 1A3E0191496;
	Wed,  9 Oct 2024 11:05:22 +0000 (UTC)
Authentication-Results: smtp.subspace.kernel.org;
	dkim=pass (2048-bit key) header.d=kernel.org header.i=@kernel.org header.b="NxYb88W0"
Received: from smtp.kernel.org (aws-us-west-2-korg-mail-1.web.codeaurora.org [10.30.226.201])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by smtp.subspace.kernel.org (Postfix) with ESMTPS id 7C89B1C6BE
	for <linux-kernel@vger.kernel.org>; Wed,  9 Oct 2024 11:05:21 +0000 (UTC)
Authentication-Results: smtp.subspace.kernel.org; arc=none smtp.client-ip=10.30.226.201
ARC-Seal:i=1; a=rsa-sha256; d=subspace.kernel.org; s=arc-20240116;
	t=1728471921; cv=none; b=T4eL5uff3LQl940gVjHh08/w+NjNxkBi03erJHeLKIeA9+Vm2xahtUe0/DQqdZSmk7e15KqNWnvWVwSql24qa6BBowm6jnYy3UZOi5DjjRIXcR+Xt+eB80wiaHZuMnSgsqOmbK4syEiDlCsQWG8dVr8IA+dXPIvzNbHVX3J/nnI=
ARC-Message-Signature:i=1; a=rsa-sha256; d=subspace.kernel.org;
	s=arc-20240116; t=1728471921; c=relaxed/simple;
	bh=6XbZgR83m/0tqAHP6Iz5wI7T504cypNosEUxPvNNVZU=;
	h=Date:Message-ID:From:To:Cc:Subject:In-Reply-To:References:
	 MIME-Version:Content-Type; b=IcGUd6+0e2xTueG8/HCM3KXwpmVyY2GzFF46NnukLpr9p6zIx3qt9NXXFnOe/DZbwpl+7MzwGrb+RvDWpQQOnCIcL+bS+534L+rc6iyTrePHcR16PkFPqYaF6d85AoqQWSiu8k2Y7KQj3q15I+H2rZcJhdiIeYg7tgvC48rZ7aY=
ARC-Authentication-Results:i=1; smtp.subspace.kernel.org; dkim=pass (2048-bit key) header.d=kernel.org header.i=@kernel.org header.b=NxYb88W0; arc=none smtp.client-ip=10.30.226.201
Received: by smtp.kernel.org (Postfix) with ESMTPSA id 1E707C4CEC5;
	Wed,  9 Oct 2024 11:05:21 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=kernel.org;
	s=k20201202; t=1728471921;
	bh=6XbZgR83m/0tqAHP6Iz5wI7T504cypNosEUxPvNNVZU=;
	h=Date:From:To:Cc:Subject:In-Reply-To:References:From;
	b=NxYb88W0fmD7vbWpDmLty06Eo01CgKyfaa+ZE/71KNgOkaDbSKHngYvorQWz5hhYz
	 CVZo6fO6uot5pLUQ69Hzhnn4ig2M7iYSQxr42oa2uD3GN3tPcw7DPM5ZFjEOwlLnBc
	 9pMEd3VhIAkilKANhoP0q5ehVsN0cnJ813HGc1T1MollhTt2+wNY77FsRNfakDUrap
	 x0fq/XQQUs5NG31uBAktMKIOk1hs0ullpmxNkVbqYkx7HYMIq+fEkyufPJMh49b8/g
	 TZL+qe+6mlgDRBgqY5a3MCrQO7ijXD5yytvRtUbGp1nL+kov/iG5kmR+nRMELpRv7d
	 JTBVK73zlguaQ==
Received: from sofa.misterjones.org ([185.219.108.64] helo=goblin-girl.misterjones.org)
	by disco-boy.misterjones.org with esmtpsa  (TLS1.3) tls TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
	(Exim 4.95)
	(envelope-from <maz@kernel.org>)
	id 1syUVK-001nkW-QJ;
	Wed, 09 Oct 2024 12:05:18 +0100
Date: Wed, 09 Oct 2024 12:05:17 +0100
Message-ID: <86ttdl5yfm.wl-maz@kernel.org>
From: Marc Zyngier <maz@kernel.org>
To: Lorenzo Pieralisi <lpieralisi@kernel.org>
Cc: linux-kernel@vger.kernel.org,
	linux-arm-kernel@lists.infradead.org,
	Thomas Gleixner <tglx@linutronix.de>
Subject: Re: [PATCH] drivers: irqchip: Remove ARM_GIC_V3_ITS_PCI Kconfig leftover
In-Reply-To: <20241009101533.189093-1-lpieralisi@kernel.org>
References: <20241009101533.189093-1-lpieralisi@kernel.org>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI-EPG/1.14.7 (Harue)
 FLIM-LB/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL-LB/10.8 EasyPG/1.0.0 Emacs/29.4
 (aarch64-unknown-linux-gnu) MULE/6.0 (HANACHIRUSATO)
Precedence: bulk
X-Mailing-List: linux-kernel@vger.kernel.org
List-Id: <linux-kernel.vger.kernel.org>
List-Subscribe: <mailto:linux-kernel+subscribe@vger.kernel.org>
List-Unsubscribe: <mailto:linux-kernel+unsubscribe@vger.kernel.org>
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=US-ASCII
X-SA-Exim-Connect-IP: 185.219.108.64
X-SA-Exim-Rcpt-To: lpieralisi@kernel.org, linux-kernel@vger.kernel.org, linux-arm-kernel@lists.infradead.org, tglx@linutronix.de
X-SA-Exim-Mail-From: maz@kernel.org
X-SA-Exim-Scanned: No (on disco-boy.misterjones.org); SAEximRunCond expanded to false

On Wed, 09 Oct 2024 11:15:33 +0100,
Lorenzo Pieralisi <lpieralisi@kernel.org> wrote:
> 
> GICv3 ITS PCI handling code moved to the MSI parent infrastructure in:
> 
> commit b5712bf89b4b ("irqchip/gic-v3-its: Provide MSI parent for
> PCI/MSI[-X]")
> 
> the code move removed source files that were selected by the
> the ARM_GIC_V3_ITS_PCI config option; it now sits unused.
> 
> Remove it.
> 
> Fixes: b5712bf89b4b ("irqchip/gic-v3-its: Provide MSI parent for PCI/MSI[-X]")
> Signed-off-by: Lorenzo Pieralisi <lpieralisi@kernel.org>
> Cc: Thomas Gleixner <tglx@linutronix.de>
> Cc: Marc Zyngier <maz@kernel.org>

Already fixed as of:

https://lore.kernel.org/r/172787481077.390.6867959419187258610.tip-bot2@tip-bot2

Thanks,

	M.

-- 
Without deviation from the norm, progress is not possible.

