Return-Path: <linux-kernel+bounces-342906-lists+linux-kernel=lfdr.de@vger.kernel.org>
X-Original-To: lists+linux-kernel@lfdr.de
Delivered-To: lists+linux-kernel@lfdr.de
Received: from sy.mirrors.kernel.org (sy.mirrors.kernel.org [IPv6:2604:1380:40f1:3f00::1])
	by mail.lfdr.de (Postfix) with ESMTPS id CD117989499
	for <lists+linux-kernel@lfdr.de>; Sun, 29 Sep 2024 11:38:46 +0200 (CEST)
Received: from smtp.subspace.kernel.org (wormhole.subspace.kernel.org [52.25.139.140])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by sy.mirrors.kernel.org (Postfix) with ESMTPS id 85887B232F5
	for <lists+linux-kernel@lfdr.de>; Sun, 29 Sep 2024 09:38:44 +0000 (UTC)
Received: from localhost.localdomain (localhost.localdomain [127.0.0.1])
	by smtp.subspace.kernel.org (Postfix) with ESMTP id A5EEA144D0C;
	Sun, 29 Sep 2024 09:38:39 +0000 (UTC)
Authentication-Results: smtp.subspace.kernel.org;
	dkim=pass (2048-bit key) header.d=kernel.org header.i=@kernel.org header.b="bz9WR7m9"
Received: from smtp.kernel.org (aws-us-west-2-korg-mail-1.web.codeaurora.org [10.30.226.201])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by smtp.subspace.kernel.org (Postfix) with ESMTPS id 0C3031428FA;
	Sun, 29 Sep 2024 09:38:38 +0000 (UTC)
Authentication-Results: smtp.subspace.kernel.org; arc=none smtp.client-ip=10.30.226.201
ARC-Seal:i=1; a=rsa-sha256; d=subspace.kernel.org; s=arc-20240116;
	t=1727602719; cv=none; b=p1jhcxHhASvdC+jptrM5jGLsJIy1/trU+2mmIrTUxdc7GzHU3KorbLTe/u3knzRqPyDDPk6irwj4uusMcGoykgLzslWQaD3zCQckqxjQeelcWfCuaU91dybswd2IofCVM3qhm2JWV6cSuJIYmqNDz3kS6BBEF6D3XIuEQYH/kVA=
ARC-Message-Signature:i=1; a=rsa-sha256; d=subspace.kernel.org;
	s=arc-20240116; t=1727602719; c=relaxed/simple;
	bh=kl8V5IsDsE3p1fGajjYA/Y3X9DNawVe6buZRKJlZ7iw=;
	h=Date:Message-ID:From:To:Cc:Subject:In-Reply-To:References:
	 MIME-Version:Content-Type; b=HZD+onO9rLhLb4LeSS4P3bX1YdW5DM3oumsNDNDQjpjbr0UCWGlpZZXDFnka/ayXo2ZmQ2+funMKPqgSoM9viLq744gyGnuMZiViyt/3Ka87wNJAOcd/3Hqt704LNnWqweKxbU5ebMUe2JWow/Tuy/U+uOQPJglakXhFe9bqU5c=
ARC-Authentication-Results:i=1; smtp.subspace.kernel.org; dkim=pass (2048-bit key) header.d=kernel.org header.i=@kernel.org header.b=bz9WR7m9; arc=none smtp.client-ip=10.30.226.201
Received: by smtp.kernel.org (Postfix) with ESMTPSA id 75B29C4CEC5;
	Sun, 29 Sep 2024 09:38:38 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=kernel.org;
	s=k20201202; t=1727602718;
	bh=kl8V5IsDsE3p1fGajjYA/Y3X9DNawVe6buZRKJlZ7iw=;
	h=Date:From:To:Cc:Subject:In-Reply-To:References:From;
	b=bz9WR7m9Kw5OQPzaPSrqyRf75yLGjyHVrsNohzqKtyUJB3menm2ztv0U2ujiGl37V
	 QQsc7Lr9O8pN4YnDhCsYLwbe5yGJV3BQ+cDzufBDwYtOeu6PR/v1PV41aFbxqMw21m
	 lM/siBpUU0joceQ/nzzCrzIvbW+X6Nc0UCidhhVPggT67/DDKx6JB9pTCZ22q1jzQB
	 bw3zHhSst0FYG3UmOqHwCRgm+9q9NhgHmf7YqFhZsDlNsiStHBBB5i4MQyHeuB0eS7
	 E47ypMRXYjrLdMrSehLWHndlCD2+tZfpJUdyaaM5Jv/Iz1BFk6JYCmIppceYMFMVrr
	 li8268Cy/PXLA==
Received: from [185.143.37.16] (helo=wait-a-minute.misterjones.org)
	by disco-boy.misterjones.org with esmtpsa  (TLS1.3) tls TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
	(Exim 4.95)
	(envelope-from <maz@kernel.org>)
	id 1suqNw-00GC4u-0U;
	Sun, 29 Sep 2024 10:38:36 +0100
Date: Sun, 29 Sep 2024 10:38:35 +0100
Message-ID: <87v7yevlyc.wl-maz@kernel.org>
From: Marc Zyngier <maz@kernel.org>
To: jiaqingtong97@gmail.com
Cc: Oliver Upton <oliver.upton@linux.dev>,
	James Morse <james.morse@arm.com>,
	Suzuki K Poulose <suzuki.poulose@arm.com>,
	Zenghui Yu <yuzenghui@huawei.com>,
	Catalin Marinas <catalin.marinas@arm.com>,
	Will Deacon <will@kernel.org>,
	Joey Gouly <joey.gouly@arm.com>,
	Jia Qingtong <jiaqingtong@huawei.com>,
	linux-arm-kernel@lists.infradead.org,
	kvmarm@lists.linux.dev,
	linux-kernel@vger.kernel.org
Subject: Re: [PATCH] KVM: arm64: vgic: fix GICR_STATUSR in vgic_v3_rd_registers
In-Reply-To: <20240929043937.242769-2-jiaqingtong97@gmail.com>
References: <20240929043937.242769-2-jiaqingtong97@gmail.com>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI-EPG/1.14.7 (Harue)
 FLIM-LB/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL-LB/10.8 EasyPG/1.0.0 Emacs/29.4
 (x86_64-pc-linux-gnu) MULE/6.0 (HANACHIRUSATO)
Precedence: bulk
X-Mailing-List: linux-kernel@vger.kernel.org
List-Id: <linux-kernel.vger.kernel.org>
List-Subscribe: <mailto:linux-kernel+subscribe@vger.kernel.org>
List-Unsubscribe: <mailto:linux-kernel+unsubscribe@vger.kernel.org>
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=US-ASCII
X-SA-Exim-Connect-IP: 185.143.37.16
X-SA-Exim-Rcpt-To: jiaqingtong97@gmail.com, oliver.upton@linux.dev, james.morse@arm.com, suzuki.poulose@arm.com, yuzenghui@huawei.com, catalin.marinas@arm.com, will@kernel.org, joey.gouly@arm.com, jiaqingtong@huawei.com, linux-arm-kernel@lists.infradead.org, kvmarm@lists.linux.dev, linux-kernel@vger.kernel.org
X-SA-Exim-Mail-From: maz@kernel.org
X-SA-Exim-Scanned: No (on disco-boy.misterjones.org); SAEximRunCond expanded to false

On Sun, 29 Sep 2024 05:39:35 +0100,
jiaqingtong97@gmail.com wrote:
> 
> From: Jia Qingtong <jiaqingtong@huawei.com>
> 
> vgic_uaccess use bsearch search regs in vgic_io_device.regions, but the
> GICR_STATUSR have wrong order in vgic_v3_rd_registers.
> When check all vgic_register_region, it turned out that only
> vgic_v3_rd_registers has this problem.
> 
> It's harmless since vgic_uaccess behaves as RAZ&WI when it can't find the
> specified reg. This is exactly the same as the behavior of the GICR_STATUSR
> register.
>
> So just move GICR_STATUSR to the right place.

That looks correct, but I think we should have some code that ensures
that these tables are correct at boot time, just like we're doing for
the system registers. Or completely remove our reliance on bsearch().

Another thing is that GICD_STATUSR looks pretty wrong. It is handled
as RAO, but we never clear any "error" (it is WI). This has been buggy
since GICv3 save/restore was added, 7 years ago.

Do you mind spinning a series fixing this up?

Thanks,

	M.

-- 
Without deviation from the norm, progress is not possible.

